### ISSUE TITLE
Empty commands and queries

### ISSUE THREAD

**Issue by mattiasnordqvist** [carl-berg/appeaser#12]
I often find myself creating ampty query and command objects. They simply do not need any properties because their respective handlers doesn't. So I have a lot om empty classes lying around just so that the Mediator can determine which handler to invoke. Would it be possible to create some default Command/Query objects with a type reference or something to find the handler to be used?

**Comment by carl-berg** [comment]
Should be possible by tinkering with the `Mediator.GetHandler`. Maybe you could subclass Mediator and override that method?

**Comment by mattiasnordqvist** [comment]
Didn't even have to bother with subclassing. This was enough:

```csharp
 public class EmptyQuery<T, TResult> : IAsyncQuery<TResult>
      where T : IAsyncQueryHandler<EmptyQuery<T, TResult>, TResult>
{
}

public class Handler : IAsyncQueryHandler<EmptyQuery<Handler, Result>, Result>
{
    ...
    public async Task<Result> Handle(EmptyQuery<Handler, Result> command)
    {
        ...
    }
}
```

**Comment by mattiasnordqvist** [comment]
But maybe this is negating what's good with the mediator pattern to begin with? Because now I have to 

```csharp
_mediator.Request(new Q<Handler, Result>())
```

specifying explicitly which handler to use.

**Comment by carl-berg** [comment]
Seems ok with me. Myself i don't mind so much empty classes fom requests, if their name signifies what the expected result is.
