### ISSUE TITLE
Are we loosing our stack trace here?

### ISSUE THREAD

**Issue by mattiasnordqvist** [carl-berg/appeaser#28]
Are we loosing our stack trace here?
https://github.com/carl-berg/appeaser/blob/5e1173e739819d40f2023a358c85d7e5f616b5b0/src/Appeaser/Interception/MediatorInterceptor.cs#L45

**Comment by mattiasnordqvist** [comment]
same here:
https://github.com/carl-berg/appeaser/blob/5e1173e739819d40f2023a358c85d7e5f616b5b0/src/Appeaser/Interception/MediatorInterceptor.cs#L76

**Comment by carl-berg** [comment]
Yup, we do. Should be changed to a `throw` to preserve stack information

**Comment by carl-berg** [comment]
Seems like we can use `ExceptionDispatchInfo.Capture(exception).Throw();` to rethrow the unwrapped exception without losing stack trace

**Comment by carl-berg** [comment]
Fixed in [Release 2.3.3](https://github.com/carl-berg/appeaser/releases/tag/2.3.3)

**Comment by mattiasnordqvist** [comment]
Knew there was something like that but I've never used it myself!
